export const CREATE_CLINIC_REQUEST = "CREATE_CLINIC_REQUEST";
export const CREATE_CLINIC_SUCCESS = "CREATE_CLINIC_SUCCESS";
export const CREATE_CLINIC_FAILURE = "CREATE_CLINIC_FAILURE";

export const UPDATE_CLINIC_REQUEST = "UPDATE_CLINIC_REQUEST";
export const UPDATE_CLINIC_SUCCESS = "UPDATE_CLINIC_SUCCESS";
export const UPDATE_CLINIC_FAILURE = "UPDATE_CLINIC_FAILURE";

export const FETCH_CLINICS_REQUEST = "FETCH_CLINICS_REQUEST";
export const FETCH_CLINICS_SUCCESS = "FETCH_CLINICS_SUCCESS";
export const FETCH_CLINICS_FAILURE = "FETCH_CLINICS_FAILURE";

export const FETCH_CLINIC_BY_ID_REQUEST = "FETCH_CLINIC_BY_ID_REQUEST";
export const FETCH_CLINIC_BY_ID_SUCCESS = "FETCH_CLINIC_BY_ID_SUCCESS";
export const FETCH_CLINIC_BY_ID_FAILURE = "FETCH_CLINIC_BY_ID_FAILURE";

export const FETCH_CLINIC_BY_OWNER_REQUEST = "FETCH_CLINIC_BY_OWNER_REQUEST";
export const FETCH_CLINIC_BY_OWNER_SUCCESS = "FETCH_CLINIC_BY_OWNER_SUCCESS";
export const FETCH_CLINIC_BY_OWNER_FAILURE = "FETCH_CLINIC_BY_OWNER_FAILURE";

export const SEARCH_CLINICS_REQUEST = "SEARCH_CLINICS_REQUEST";
export const SEARCH_CLINICS_SUCCESS = "SEARCH_CLINICS_SUCCESS";
export const SEARCH_CLINICS_FAILURE = "SEARCH_CLINICS_FAILURE";

export const DELETE_CLINIC_REQUEST = "DELETE_CLINIC_REQUEST";
export const DELETE_CLINIC_SUCCESS = "DELETE_CLINIC_SUCCESS";
export const DELETE_CLINIC_FAILURE = "DELETE_CLINIC_FAILURE";
