server:
  port: ${SERVER_PORT}

spring:
  application:
    name: ${SPRING_APPLICATION_NAME}

eureka:
  instance:
    hostname: ${EUREKA_HOSTNAME}
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: ${EUREKA_DEFAULT_ZONE}
