export const CREATE_BOOKING_REQUEST = "CREATE_BOOKING_REQUEST";
export const CREATE_BOOKING_SUCCESS = "CREATE_BOOKING_SUCCESS";
export const CREATE_BOOKING_FAILURE = "CREATE_BOOKING_FAILURE";

export const FETCH_CUSTOMER_BOOKINGS_REQUEST = "FETCH_CUSTOMER_BOOKINGS_REQUEST";
export const FETCH_CUSTOMER_BOOKINGS_SUCCESS = "FETCH_CUSTOMER_BOOKINGS_SUCCESS";
export const FETCH_CUSTOMER_BOOKINGS_FAILURE = "FETCH_CUSTOMER_BOOKINGS_FAILURE";

export const FETCH_CLINIC_BOOKINGS_REQUEST = "FETCH_CLINIC_BOOKINGS_REQUEST";
export const FETCH_CLINIC_BOOKINGS_SUCCESS = "FETCH_CLINIC_BOOKINGS_SUCCESS";
export const FETCH_CLINIC_BOOKINGS_FAILURE = "FETCH_CLINIC_BOOKINGS_FAILURE";

export const FETCH_BOOKING_BY_ID_REQUEST = "FETCH_BOOKING_BY_ID_REQUEST";
export const FETCH_BOOKING_BY_ID_SUCCESS = "FETCH_BOOKING_BY_ID_SUCCESS";
export const FETCH_BOOKING_BY_ID_FAILURE = "FETCH_BOOKING_BY_ID_FAILURE";

export const UPDATE_BOOKING_STATUS_REQUEST = "UPDATE_BOOKING_STATUS_REQUEST";
export const UPDATE_BOOKING_STATUS_SUCCESS = "UPDATE_BOOKING_STATUS_SUCCESS";
export const UPDATE_BOOKING_STATUS_FAILURE = "UPDATE_BOOKING_STATUS_FAILURE";

export const GET_CLINIC_REPORT_REQUEST = 'GET_CLINIC_REPORT_REQUEST';
export const GET_CLINIC_REPORT_SUCCESS = 'GET_CLINIC_REPORT_SUCCESS';
export const GET_CLINIC_REPORT_FAILURE = 'GET_CLINIC_REPORT_FAILURE';

export const FETCH_BOOKED_SLOTS_REQUEST = "FETCH_BOOKED_SLOTS_REQUEST";
export const FETCH_BOOKED_SLOTS_SUCCESS = "FETCH_BOOKED_SLOTS_SUCCESS";
export const FETCH_BOOKED_SLOTS_FAILURE = "FETCH_BOOKED_SLOTS_FAILURE";

export const UPDATE_BOOKING_SLOT_REQUEST = "UPDATE_BOOKING_SLOT_REQUEST";
export const UPDATE_BOOKING_SLOT_SUCCESS = "UPDATE_BOOKING_SLOT_SUCCESS";
export const UPDATE_BOOKING_SLOT_FAILURE = "UPDATE_BOOKING_SLOT_FAILURE";




export const FETCH_ALL_BOOKINGS_REQUEST = "FETCH_ALL_BOOKINGS_REQUEST";
export const FETCH_ALL_BOOKINGS_SUCCESS = "FETCH_ALL_BOOKINGS_SUCCESS";
export const FETCH_ALL_BOOKINGS_FAILURE = "FETCH_ALL_BOOKINGS_FAILURE";

export const FETCH_BOOKING_CHART_REQUEST = "FETCH_BOOKING_CHART_REQUEST";
export const FETCH_BOOKING_CHART_SUCCESS = "FETCH_BOOKING_CHART_SUCCESS";
export const FETCH_BOOKING_CHART_FAILURE = "FETCH_BOOKING_CHART_FAILURE";

export const SEARCH_BOOKINGS_REQUEST = "SEARCH_BOOKINGS_REQUEST";
export const SEARCH_BOOKINGS_SUCCESS = "SEARCH_BOOKINGS_SUCCESS";
export const SEARCH_BOOKINGS_FAILURE = "SEARCH_BOOKINGS_FAILURE";


export const DELETE_BOOKING_REQUEST = "DELETE_BOOKING_REQUEST";
export const DELETE_BOOKING_SUCCESS = "DELETE_BOOKING_SUCCESS";
export const DELETE_BOOKING_FAILURE = "DELETE_BOOKING_FAILURE";


// Without pagination booking list (dashboard ke liye)
export const FETCH_ALL_BOOKINGS_NO_PAGINATION_REQUEST = "FETCH_ALL_BOOKINGS_NO_PAGINATION_REQUEST";
export const FETCH_ALL_BOOKINGS_NO_PAGINATION_SUCCESS = "FETCH_ALL_BOOKINGS_NO_PAGINATION_SUCCESS";
export const FETCH_ALL_BOOKINGS_NO_PAGINATION_FAILURE = "FETCH_ALL_BOOKINGS_NO_PAGINATION_FAILURE";
