export const CREATE_SERVICE_REQUEST = "CREATE_SERVICE_REQUEST";
export const CREATE_SERVICE_SUCCESS = "CREATE_SERVICE_SUCCESS";
export const CREATE_SERVICE_FAILURE = "CREATE_SERVICE_FAILURE";

export const UPDATE_SERVICE_REQUEST = "UPDATE_SERVICE_REQUEST";
export const UPDATE_SERVICE_SUCCESS = "UPDATE_SERVICE_SUCCESS";
export const UPDATE_SERVICE_FAILURE = "UPDATE_SERVICE_FAILURE";

export const FETCH_SERVICES_BY_CLINIC_REQUEST = "FETCH_SERVICES_BY_CLINIC_REQUEST";
export const FETCH_SERVICES_BY_CLINIC_SUCCESS = "FETCH_SERVICES_BY_CLINIC_SUCCESS";
export const FETCH_SERVICES_BY_CLINIC_FAILURE = "FETCH_SERVICES_BY_CLINIC_FAILURE";

export const FETCH_SERVICE_BY_ID_REQUEST = "FETCH_SERVICE_BY_ID_REQUEST";
export const FETCH_SERVICE_BY_ID_SUCCESS = "FETCH_SERVICE_BY_ID_SUCCESS";
export const FETCH_SERVICE_BY_ID_FAILURE = "FETCH_SERVICE_BY_ID_FAILURE";

export const DELETE_SERVICE_REQUEST = "DELETE_SERVICE_REQUEST";
export const DELETE_SERVICE_SUCCESS = "DELETE_SERVICE_SUCCESS";
export const DELETE_SERVICE_FAILURE = "DELETE_SERVICE_FAILURE";

export const SEARCH_CLINICS_BY_SERVICE_REQUEST = "SEARCH_CLINICS_BY_SERVICE_REQUEST";
export const SEARCH_CLINICS_BY_SERVICE_SUCCESS = "SEARCH_CLINICS_BY_SERVICE_SUCCESS";
export const SEARCH_CLINICS_BY_SERVICE_FAILURE = "SEARCH_CLINICS_BY_SERVICE_FAILURE";


